name: Test

on:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      publish:
        default: false
        description: Publish package
        required: false 
        type: boolean

jobs:
  build:
    name: Build native libraries
    strategy:
      matrix:
        include:
          - library: libeth_pairings.so
            os: ubuntu
            rid: linux-arm64
            target: aarch64-unknown-linux-gnu
          - library: libeth_pairings.so
            os: ubuntu
            rid: linux-x64
            target: x86_64-unknown-linux-gnu
          #- library: libeth_pairings.dylib
          #  os: macos
          #  rid: osx-arm64
          #  target: aarch64-apple-darwin
          #- library: libeth_pairings.dylib
          #  os: macos
          #  rid: osx-x64
          #  target: x86_64-apple-darwin
          #- library: eth_pairings.dll
          #  os: windows
          #  rid: win-x64
          #  target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}-20.04
    steps:
      - name: Check out eip1962 repository
        uses: actions/checkout@v3
        with:
          repository: nethermindeth/eip1962
          ref: feature/bindings
          path: eth_pairings

      - name: Set up GNU C compiler for arm64
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Set up Rust
        run: |
          rustup update
          rustup target add ${{ matrix.target }}

      - name: Build
        working-directory: eth_pairings
        run: |
          docker pull rust:buster
          docker run --rm --user "$(id -u)":"$(id -g)" -v "$PWD":$GITHUB_WORKSPACE/eth_pairings -w $GITHUB_WORKSPACE/eth_pairings rust:buster cargo build --release--target ${{ matrix.target }} --features eip_196_c_api,eip_2357_c_api
          #cargo build --release --target ${{ matrix.target }} --features eip_196_c_api,eip_2357_c_api

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.rid }}
          path: eth_pairings/target/${{ matrix.target }}/release/${{ matrix.library }}
          retention-days: 2
          if-no-files-found: error

  
